#
# Amazon EC2 example cluster configuration
#
ectwo:
    - image "eu-west-1/ami-97344ae0"		# Ubuntu 14.04 LTS AMI
    - region "eu-west-1"					# Region
    - m1.medium {ZK, WORKER, MASTER, UI}	# Request service
    - m1.medium {ZK, WORKER}				# Request service
    - m1.medium {ZK, WORKER}				# Request service
    - m1.medium {WORKER}					# Request service
    - remote-exec-preconfig {cd ~, echo hey > hey.txt}
    - remote-exec-postconfig {}
    - ssh-key-name "mySSHKeyName"           # Optional. defaults to "id_rsa"
    - storm-deploy-alternative-cloud-jar-url "https://s3-eu-west-1.amazonaws.com/storm-deploy-alternative-cloud.jar"
    - storm-tar-gz-url "http://mirror.yannic-bonenberger.com/apache/storm/apache-storm-0.9.3/apache-storm-0.9.3.tar.gz" # https://storm.apache.org/downloads.html
    - zk-tar-gz-url "http://apache.lauf-forum.at/zookeeper/zookeeper-3.4.7/zookeeper-3.4.7.tar.gz" # https://www.apache.org/dyn/closer.cgi/zookeeper/